#!/usr/bin/php
<?php
	/* Copyright (C) by Hugo Leisink <hugo@leisink.net>
	 * This file is part of the Banshee PHP framework
	 * https://www.banshee-php.org/
	 *
	 * Licensed under The MIT License
	 */

	chdir(__DIR__);
	require("libraries/core/banshee.php");

	$written_for = "6.1";

	/* Auditor class
	 */
	abstract class auditor {
		protected $extension = null;
		protected $sub_directories = array(".");
		private $current_directory = null;
		private $dp = false;
		protected $verified = array();
		private $exclude = array("./public", "./templates");

		/* Destructor
		 *
		 * INPUT:  -
		 * OUTPUT: -
		 * ERROR:  -
		 */
		public function __destruct() {
			if ($this->dp !== false) {
				closedir($this->dp);
			}
		}

		/* Next file
		 *
		 * INPUT:  -
		 * OUTPUT: string filename
		 * ERROR:  false
		 */
		protected function next_file() {
			$file = false;

			do {
				if ($this->dp == false) {
					if (count($this->sub_directories) == 0) {
						return false;
					}
					$this->current_directory = array_shift($this->sub_directories);
					$this->dp = opendir($this->current_directory);

					continue;
				}

				if (($file = readdir($this->dp)) == false) {
					closedir($this->dp);
					$this->dp = false;
					continue;
				}

				if ($file[0] == ".") {
					$file = false;
					continue;
				}

				$file = $this->current_directory."/".$file;
				if (is_dir($file)) {
					foreach ($this->exclude as $exclude) {
						if (substr($file, 0, strlen($exclude)) == $exclude) {
							$file = false;
							continue 2;
						}
					}
					array_push($this->sub_directories, $file);
					$file = false;
					continue;
				}

				if ($this->extension !== null) {
					$info = pathinfo($file);
					if ($info["extension"] != $this->extension) {
						$file = false;
						continue;
					}
				}
			} while ($file === false);

			if (substr($file, 0, 2) == "./") {
				$file = substr($file, 2);
			}

			return $file;
		}

		/* Scan file dummy function
		 *
		 * INPUT:  string line
		 * OUTPUT: -
		 * ERROR:  -
		 */
		protected function scan_line($line) {
		}

		/* Scan file
		 *
		 * INPUT:  string filename
		 * OUTPUT: bool issue found
		 * ERROR:  -
		 */
		protected function scan_file($file) {
			$lines = file($file);

			$results = array();
			foreach ($lines as $number => $line) {
				$number++;
				$line = trim($line);

				if (substr($file, 0, 8) == "banshee/") {
					$index = substr($file, 8);
				} else {
					$index = $file;
				}

				if (is_array($this->verified[$index])) {
					if (in_array($number, $this->verified[$index])) {
						continue;
					}
				}

				if (trim($line) == "") {
					continue;
				} else if (($line[0] == "#") || (substr($line, 0, 2) == "//")) {
					continue;
				}

				ob_start();

				$this->scan_line(strtolower($line), $number);

				if (($output = ob_get_clean()) == "") {
					continue;
				}

				$output = explode("\n", trim($output));
				foreach ($output as $line) {
					array_push($results, $number.": ".$line);
				}
			}

			if (($count = count($results)) > 0) {
				$total += $count;

				print "  ".$file.":\n";
				foreach ($results as $line) {
					print "    ".$line."\n";
				}

				return true;
			}

			return false;
		}

		/* Perform audit
		 *
		 * INPUT:  -
		 * OUTPUT: -
		 * ERROR:  -
		 */
		public function perform_audit() {
			$total = 0;

			while (($file = $this->next_file()) != false) {
				if ($this->scan_file($file)) {
					$total++;
				}
			}

			if ($total == 0) {
				print "  no issues found\n";
			}
		}
	}

	/* Database auditing
	 */
	class database_auditor extends auditor {
		protected $extension = "php";
		private $variables = array();
		private $continue_var = null;
		protected $verified = array(
			"libraries/database/mysqli_connection.php"     => array(38),
			"libraries/database/postgresql_connection.php" => array(48),
			"libraries/core/user.php"                      => array(269, 278),
			"libraries/core/security.php"                  => array(192, 258),
			"libraries/tablemanager_controller.php"        => array(215),
			"libraries/tablemanager_model.php"             => array(287),
			"models/cms/link.php"                          => array(44),
			"models/cms/photos/photo.php"                  => array(214),
			"models/cms/settings.php"                      => array(61, 84),
			"models/cms/user.php"                          => array(15),
			"models/cms/webshop/article.php"               => array(46),
			"models/search.php"                            => array(142),
			"models/setup.php"                             => array(147),
			"models/webshop/cart.php"                      => array(21));

		protected function scan_line($line) {
			/* PHP database query function calls
			 */
			$forbidden = array("mysql_query", "mysqli_query", "pg_query", "sqlite_query", "mssql_query");
			foreach ($forbidden as $function) {
				if (preg_match('/'.$function.' *\(/', $line) == 1) {
					print $function."() detected\n";
				}
			}

			/* Variable content continues from previous line
			 */
			if ($this->continue_var !== null) {
				$this->variables[$this->continue_var] .= $line;

				if (substr(rtrim($line), -1) != ".") {
					$this->continue_var = null;
				}

				return;
			}

			/* Variable declaration
			 */
			if (preg_match('/^\s*\$[A-Za-z0-9_]*\s*=/', $line) == 1) {
				list($key, $value) = explode("=", $line, 2);
				$key = substr(trim($key), 1);
				$this->variables[$key] = trim($value);

				if (substr(rtrim($value), -1) == ".") {
					$this->continue_var = $key;
				}

				return;
			}

			if (preg_match('/^\s*\$[A-Za-z0-9_]*\s*\.=/', $line) == 1) {
				list($key, $value) = explode("=", $line, 2);
				$key = substr(trim($key, " ."), 1);
				$this->variables[$key] .= trim($value);

				if (substr(rtrim($value), -1) == ".") {
					$this->continue_var = $key;
				}

				return;
			}

			/* Variables included in database query string
			 */
			$pos = false;
			if (($pos = strpos($line, "db->query(")) !== false) {
				$pos += 10;
			} else if (($pos = strpos($line, "db->execute(")) !== false) {
				$pos += 12;
			}
			if ($pos !== false) {
				$str = substr($line, $pos);

				$open = 0;
				for ($i = 0; $i < strlen($line); $i++) {
					if ($str[$i] == "(") {
						$open++;
					} else if ($str[$i] == ")") {
						if ($open == 0) {
							$str = substr($str, 0, $i);
							break;
						}
						$open--;
					}
				}

				if ($str[0] == '"') {
					/* Query string is text
					 */
					foreach ($this->variables as $key => $value) {
						if (preg_match('/\.\s*\$'.$key.'/', $str) == 1) {
							print "include in query string\n";
							break;
						}
					}

					$str = str_replace('\"', "'", $str);
					list(, $str) = explode('"', $str);

					foreach ($this->variables as $key => $value) {
						if (strpos($str, "$".$key) !== false) {
							print "include in query string\n";
							break;
						}
					}
				} else if ($str[0] == "$") {
					/* Query string is variable
					 */
					list($str) = explode(",", $str);
					foreach ($this->variables as $key => $value) {
						if (strpos($str, "$".$key) !== false) {
							if (strpos($value, "\$") !== false) {
								print "include in query string\n";
							}
						}
					}

					$str = substr(trim($str), 1);
					if (isset($this->variables[$str]) == false) {
						print "unknown variable for query string: ".$str."\n";
					}
				} else {
					/* Weird query string
					 */
					print "suspicious query string\n";
				}
			}
		}
	}

	/* Output auditing
	 */
	class output_auditor extends auditor {
		protected $extension = "xslt";
		protected $verified = array(
			"views/agenda.xslt"                    => array(34, 95),
			"views/banshee/functions.xslt"         => array(24),
			"views/banshee/main.xslt"              => array(20),
			"views/banshee/page.xslt"              => array(21),
			"views/cms/webshop/order.xslt"         => array(39, 88, 96),
			"views/cms/webshop/article.xslt"       => array(41, 87),
			"views/demos/googlemaps.xslt"          => array(14),
			"views/demos/posting.xslt"             => array(19),
			"views/dictionary.xslt"                => array(69),
			"views/faq.xslt"                       => array(27),
			"views/forum.xslt"                     => array(92),
			"views/guestbook.xslt"                 => array(30),
			"views/mailbox.xslt"                   => array(51),
			"views/news.xslt"                      => array(29),
			"views/weblog.xslt"                    => array(36, 66),
			"views/webshop.xslt"                   => array(33, 57),
			"views/webshop/checkout.xslt"          => array(89, 97),
			"views/webshop/cart.xslt"              => array(34, 44),
			"views/webshop/orders.xslt"            => array(49, 57));

		protected function scan_line($line) {
			if (strpos($line, "disable-output-escaping=\"yes\"") !== false) {
				print "output escaping disabled\n";
			}
		}
	}

	class integrity_auditor {
		private $files = array(
			"libraries/core" => array(
				"banshee.php"    => "9939f02d68b0d0aaa9c23959a3a371f6f0a2df5b",
				"security.php"   => "60258091ae5fa3781ffdaa1df0b3e5cbaa0d38b4",
				"session.php"    => "4478776517de2663e958af9f3980491471ff89fe",
				"settings.php"   => "c07c539e7015cc2d2b365f3af6b15f8e1c8720d5",
				"page.php"       => "3680941682959b23beeecd2f52ba1b7bb86daf38",
				"user.php"       => "830e8f27d9a1d85f11d9181247788b882807d379",
				"view.php"       => "b8d5642a496ba9a46f150d9ea878aa3a13f3c40f"),
			"libraries/database" => array(
				"database_connection.php" => "51e18c9b5f934d6995ab7c7be3bef03a0ce34fd9",
				"mysqli_connection.php"   => "487c90773f3d13c9d3e9b751e8974437d674c4a5"),
			"libraries" => array(
				"controller.php" => "72f57a6b65f2d0c263e166d0ef42957f4079f35d",
				"email.php"      => "f1488d7ed47cf4479bc2100def8ab645e5b1d1b7",
				"model.php"      => "493fc2b0884b18e6211aad8071557ef5267d101b"),
			"public" => array(
				"index.php"      => "7be0f552f1bb689af0b2136fbff8f7d3c3e777c9"));

		public function perform_audit() {
			$total = 0;

			foreach ($this->files as $directory => $files) {
				foreach ($files as $file => $hash) {
					$file = $directory."/".$file;
					if (sha1_file($file) != $hash) {
						print "  The file ".$file." has been changed.\n";
						$total++;
					}
				}
			}

			if ($total == 0) {
				print "  no issues found\n";
			}
		}
	}

	/* Webroot auditing
	 */
	class webroot_auditor extends auditor {
		protected $sub_directories = array("public");

		public function scan_file($file) {
			if ($file == "public/index.php") {
				return false;
			}

			$parts = explode(".", $file);
			$extension = array_pop($parts);
			if ($extension == "php") {
				print "  PHP script found in webroot: ".$file."\n";
				return true;
			}

			return false;
		}
	}

	/* Start security audit
	 */
	error_reporting(E_ALL & ~E_NOTICE);

	print "Banshee Security Audit v".$written_for."\n\n";
	print "  Note that the findings below are not necessarily a security issue. They\n";
	print "  only require extra attention from the auditor. Also note that it's not\n";
	print "  guaranteed that this tool will find all security issues.\n";
	print "\n";

	/* Check Banshee version
	 */
	if (defined("BANSHEE_VERSION") == false) {
		exit("Fatal error: no Banshee installation was found.\n");
	}
	if (BANSHEE_VERSION != $written_for) {
		print "==> Be advised! This script has been optimized for Banshee version ".$written_for.".\n";
		print "    However, this website was built upon version ".BANSHEE_VERSION.".\n\n";
	}

	/* Database auditing
	 */
	print "Database usage audit results:\n";
	$database = new database_auditor;
	$database->perform_audit();
	unset($database);

	/* Output auditing
	 */
	print "Output escaping audit results:\n";
	$output = new output_auditor;
	$output->perform_audit();
	unset($output);

	/* File integrity auditing
	 */
	print "File integrity audit results:\n";
	$integrity = new integrity_auditor;
	$integrity->perform_audit();
	unset($integrity);

	/* PHP scripts in webroot auditing
	 */
	print "Webroot audit results:\n";
	$webroot = new webroot_auditor;
	$webroot->perform_audit();
	unset($webroot);
?>
