#!/bin/bash

cd `dirname $0`/..

echo "Downloading latest version of TCPDF."
curl -s -o tcpdf.zip https://codeload.github.com/tecnickcom/TCPDF/zip/master

if [ ! -s tcpdf.zip ]; then
	rm -f tcpdf.zip
	echo "Download error."
	exit
fi

echo "Installing TCPDF."
unzip -q tcpdf.zip
mkdir -p libraries/thirdparty/tcpdf
cat TCPDF-master/tcpdf.php | sed "s/require_once(dirname(__FILE__).'.*\//require_once(dirname(__FILE__).'\/tcpdf\//" > libraries/thirdparty/tcpdf.php
cp -f TCPDF-master/tcpdf_barcodes*.php libraries/thirdparty/tcpdf
cp -f TCPDF-master/tcpdf_autoconfig.php libraries/thirdparty/tcpdf
cp -f TCPDF-master/include/*.php libraries/thirdparty/tcpdf
chmod 644 libraries/thirdparty/tcpdf/*

echo "Installing fonts."
mkdir -p extra/tcpdf_fonts
cp TCPDF-master/fonts/courier*.php extra/tcpdf_fonts
cp TCPDF-master/fonts/helvetica*.php extra/tcpdf_fonts
cp TCPDF-master/fonts/symbol.php extra/tcpdf_fonts
cp TCPDF-master/fonts/times*.php extra/tcpdf_fonts
cp TCPDF-master/fonts/zapfdingbats.php extra/tcpdf_fonts
chmod 644 extra/tcpdf_fonts/*

echo "Cleaning up."
rm -f tcpdf.zip
rm -rf TCPDF-master
