#!/bin/bash

function remove_min {
	dir=$1
	for file in `ls ${dir}/*.min.*`; do
		new=`echo ${file} | sed "s/\.min\./\./"`
		mv ${file} ${new}
	done
}

cd `dirname $0`/../public/js/jquery

if [ "$1" = "" ]; then
	echo "Usage: $0 <version>"
	exit
fi

version=$1

echo "Downloading jQuery UI version ${version}."
wget -qO jquery-ui.zip http://jqueryui.com/resources/download/jquery-ui-${version}.zip

if [ ! -s jquery-ui.zip ]; then
	rm -f jquery-ui.zip
	echo "Download error."
	exit
fi

echo "Installing new jQuery UI."
unzip jquery-ui.zip > /dev/null
rm -f jquery-ui.js
rm -f jquery.ui.*.js
rm -rf i18n
mv -f jquery-ui-${version}/ui/minified/* .
remove_min .
remove_min i18n

rm -f ../../css/jquery/*
mv -f jquery-ui-${version}/themes/base/minified/*.css ../../css/jquery
for file in `ls ../../css/jquery/*.min.*`; do
	new=`echo ${file} | sed "s/\.min\./\./"`
	cat ${file} | sed "s/url(images/url(\/images\/jquery/g" > ${new}
done

rm -f ../../images/jquery/*
mv -f jquery-ui-${version}/themes/base/minified/images/* ../../images/jquery

echo "Cleaning up."
rm -rf jquery-ui-${version}
rm -f jquery-ui.zip
