#!/bin/bash

cd `dirname $0`/../public/js

if [ "$1" = "" ]; then
	echo "Usage: $0 <version>"
	exit
fi

version=$1

echo "Downloading CKEditor version ${version}."
wget -qO ckeditor.zip http://download.cksource.com/CKEditor/CKEditor/CKEditor%20${version}/ckeditor_${version}_full.zip

if [ ! -s ckeditor.zip ]; then
	rm -f ckeditor.zip
	echo "Download error."
	exit
fi

echo "Installing CKEditor."
if [ -d ckeditor ]; then
	mv -f ckeditor ckeditor_old
fi
unzip ckeditor.zip > /dev/null
rm -rf ckeditor/samples
if [ -d ckeditor_old ]; then
	mv -f ckeditor_old/config.js ckeditor
else
	cp -f ../../extra/ckeditor_config.js ckeditor/config.js
fi

echo "Cleaning up."
rm -rf ckeditor_old
rm -f ckeditor.zip
