#!/bin/bash

cd `dirname $0`/../public/js

if [ "$1" = "" ]; then
	echo "Usage: $0 <version>"
	exit
fi

version=$1

echo "Downloading CKEditor version ${version}."
wget -qO ckeditor.zip http://download.cksource.com/CKEditor/CKEditor/CKEditor%20${version}/ckeditor_${version}_full.zip

if [ ! -s ckeditor.zip ]; then
	rm -f ckeditor.zip
	echo "Download error."
	exit
fi

echo "Installing new CKEditor."
mv -f ckeditor ckeditor_old
unzip ckeditor.zip > /dev/null
rm -rf ckeditor/samples
mv -f ckeditor_old/config.js ckeditor

echo "Cleaning up."
rm -rf ckeditor_old
rm -f ckeditor.zip
