#!/usr/bin/php
<?php
	error_reporting(E_ALL & ~E_NOTICE);

	chdir(__DIR__);
	require("../libraries/core/banshee.php");
	require("../libraries/helpers/http.php");

	class verify_referer_log {
		private $db = null;

		/* Constructor
		 */
		public function __construct($db) {
			$this->db = $db;
		}

		/* Delete a referer log
		 */
		private function delete_referer_log($referer) {
			$query = "delete from log_referers where url=%s";
			$this->db->query($query, $referer["url"]);

			printf("  - deleted\n");
		}

		/* Verify referer logs
		 */
		public function execute() {
			/* Fetch referer logs
			 */
			$query = "select * from log_referers";
			if (($referers = $this->db->execute($query, 0)) == false) {
				return;
			}

			/* Verify referer logs
			 */
			$verified = array();
			foreach ($referers as $referer) {
				if (in_array($referer["url"], $verified)) {
					continue;
				}

				printf("Checking %s...\n", $referer["url"]);
				$page = follow_http_redirects($referer["url"]);
				array_push($verified, $referer["url"]);

				/* Delete upon wrong status code
				 */
				if ($page["status"] != 200) {
					$this->delete_referer_log($referer);
					continue;
				}

				/* Delete upon missing link
				 */
				if (strpos($page["body"], WEBSITE_DOMAIN) === false) {
					$this->delete_referer_log($referer);
				} else {
					printf("  - ok\n");
				}
			}
		}
	}

	/* Connect to database
	 */
	$db = new Banshee\Database\MySQLi_connection(DB_HOSTNAME, DB_DATABASE, DB_USERNAME, DB_PASSWORD);
	if ($db->connected == false) {
		exit("Internal error: database not available.\n");
	}

	$verify = new verify_referer_log($db);
	$verify->execute();
?>
